import '@/styles/globals.css';
import { ReactNode } from 'react';
import ThemeProvider from '@/components/ui/ThemeProvider';
import Navbar from '@/components/Navbar';
import { Montserrat } from 'next/font/google';
import { cn } from '@/lib/utils';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'DaisyUI',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      className={cn(
        'antialiased transition-colors duration-200',
        montserrat.className
      )}
      lang='en'
    >
      <body>
        <ThemeProvider>
          <Navbar />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
