import '@/styles/globals.css';
import { ReactNode } from 'react';
import ThemeProvider from '@/components/ui/ThemeProvider';
import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'DaisyUI',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html className='antialiased' lang='en'>
      <body>
        <ThemeProvider>
          <Navbar />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
